### ISSUE TITLE
Callback does not support functions that are property values (?)

### ISSUE THREAD

**Issue by isker** [laverdet/isolated-vm#274] opened 2021-12-22 17:49 UTC
Not sure if "property value" is the actual determinant here, but see my test cases: https://github.com/isker/ivm-sandbox/blob/fa61a0d9eebd8c6b0fc60d47505cfae61e637f46/simple-function.test.js.

The [docs](https://github.com/laverdet/isolated-vm#class-callback-transferable) say:
> Callbacks can be used to create cross-isolate references to simple functions.

I don't know if this qualifies as a non-simple function and is thus intentionally not supported.  If that's the case, more detail in the docs as to what is supported and better error messages when passing something that's not supported would be appreciated.  ```"`setSync` requires parameter 3 to be a string"``` is pretty confusing, because the [documented](https://github.com/laverdet/isolated-vm/tree/56cc60b3486536ac3f90613fd0ec5fa58ef2c193#referencesetsyncproperty-value-options) third parameter of this function is TransferOptions.

(I verified you get the same "`setSync`" error messages in 3.3.10 so the strange error messages predate Callback.)

Thanks!

**Comment by laverdet** [comment] 2022-01-09 16:52
I think this is a dupe of #276. Console methods are spooky.

**Closed by laverdet** 2022-01-09 16:52 UTC

**Comment by isker** [comment] 2022-01-09 23:24
Agreed, thanks.
