### ISSUE TITLE
Calling callbacks from within Isolate randomly hangs it

### ISSUE THREAD

**Issue by lmcsu** [laverdet/isolated-vm#321] opened 2022-09-03 22:55 UTC
Calling callbacks from within Isolate randomly hangs it.
Reproduction is below, just run it and wait for a while.
isolated-vm 4.4.1 (current latest)
node 16.17.0 (current LTS)

Caught this also on 4.3.7, but couldn't catch on 4.3.6
So this might be related #307 

```
const ivm = require('isolated-vm');

const vm = new ivm.Isolate({
    memoryLimit: 2048,
});

const cb = new ivm.Callback(() => '123');

async function run() {
    const context = await vm.createContext();

    await context.global.set('cb', cb);

    const result = await context.eval('cb()', {
        timeout: 5000,
    });

    context.release();

    return result;
}

const loop = () => {
    let current = 0;
    const max = 1000;
    for (let i = 0; i < max; i++) {
        run().then(() => {
            console.log(++current);

            if (current === max) {
                setTimeout(loop, 500);
            }
        });
    }
};
loop();
```

**Comment by lmcsu** [comment] 2022-09-13 11:09
After 10 days of production usage I confirm that 4.3.6 works perfect.
So all the next versions are NOT FOR PRODUCTION.
It's a really critical issue.

**Comment by everhardt** [comment] 2022-10-28 08:29
@laverdet this issue (which is a duplicate of #307) has become more pressing, as node 18 has become LTS now and isolated-vm 4.3.6 does not support it. I don't have the knowledge to fix the issue 4.3.7 caused, but would you be willing to accept a PR that reverts the [probable culprit](https://github.com/laverdet/isolated-vm/commit/16b2bc18336ab3495c65b5feaef35461d540cfd5)?

**Comment by laverdet** [comment] 2022-10-28 19:01
Hi there please let me know if v4.4.2 works for you.

**Closed** 2022-10-28 19:00 UTC

**Comment by everhardt** [comment] 2022-11-01 10:41
It's running on production for a while now without any problems! 🎉
