### ISSUE TITLE
SharedArrayBuffer are retained in Isolates

### ISSUE THREAD

**Issue by legraphista** [laverdet/isolated-vm#68] opened 2018-07-04 14:50 UTC
Sample code: 
```js
const ivm = require('isolated-vm');
const v8 = require('v8');

const isolate = new ivm.Isolate();
const context = isolate.createContextSync();
context.global.setSync('ivm', ivm);
context.global.setSync('global', context.global.derefInto());

isolate.compileScriptSync('(' + (() => {

  global._do = (shared) => {
    const interpretation = new Uint8Array(shared);
    return interpretation[0];
  }

}) + ')()').runSync(context);

const ref = context.global.getSync('_do');

for (let i = 0; i < 10; i++) {

  const sharedBuffer = new SharedArrayBuffer(20 * 2 ** 20); //20MB
  const view = new Uint8Array(sharedBuffer);
  view[0] = 10;

  const result = ref.applySync(undefined, [new ivm.ExternalCopy(sharedBuffer).copyInto({
    release: true,
    transferIn: true
  })]);

  if (result !== view[0]) {
    throw new Error('different result');
  }

  console.log('isolate', isolate.getHeapStatisticsSync().externally_allocated_size);
  console.log('main', v8.getHeapStatistics().used_heap_size);
  global.gc();

}
```

By running with 
```bash
node --expose-gc leak.js
```
you will notice the `externally_allocated_size` is growing each iteration by 20MB, but the main process has a stable memory usage pattern
```
isolate 20971520
main 5115440
isolate 41943040
main 4726624
isolate 62914560
main 4721408
isolate 83886080
main 4721800
isolate 104857600
main 4685128
isolate 125829120
main 4685400
isolate 146800640
main 4685672
isolate 167772160
main 4685944
isolate 188743680
main 4686216
isolate 209715200
main 4686488
```

Is there something obvious that i'm missing?

**Comment by legraphista** [comment] 2018-07-04 15:04
I've tried to dispose of the `ExternalCopy` manually, not relying on `release` from `copyInto()`, and the issue is resolved:
```js
....
  global._do = (sharedExternal) => {
    const shared = sharedExternal.copy();
    let interpretation = new Uint8Array(shared);
    const result = interpretation[0];
    interpretation = null;
    sharedExternal.dispose();
    return result;
  }
....
  const result = ref.applySync(undefined, [new ivm.ExternalCopy(sharedBuffer)]);
....
```

**Comment by laverdet** [comment] 2018-07-05 17:34
The problem is that you're calling `gc()` from the main isolate instead of the "inner" isolate. The inner isolate will keep these buffers alive until a garbage collection is run. If you do this instead you'll find that both isolates remain stable:

```js
  global._do = (shared) => {
    const interpretation = new Uint8Array(shared);
    let tmp = interpretation[0];
    gc();
    return tmp;
  }
```

**Comment by legraphista** [comment] 2018-07-05 17:50
Ah, I see. Unfortunately I cannot control if the GC is exposed (like in the example). 
When I drop the memory limit to 128, the GC doesn't trigger itself and the isolate runs out of memory then is disposed.

**Comment by laverdet** [comment] 2018-07-06 07:40
Are you running node 10.4.0 or greater? v8 recently changed some heap limit stuff which could cause a bug like what you're seeing. If so, please try master because I just pushed a fix for that issue.

**Comment by legraphista** [comment] 2018-07-06 09:09
I was running v9.11.1 and seeing this behaviour. Unfortunately, same thing happens on latest master commit.

You will find a zip attached with a sample project for testing and logs for node version 9.11.1 and 10.6.0

[sample.zip](https://github.com/laverdet/isolated-vm/files/2169731/sample.zip)
Node 9: https://pastebin.com/raw/9zef58LG
Node 10: https://pastebin.com/raw/PSgJ8ZBL

**Comment by laverdet** [comment] 2018-07-06 18:41
I could force a garbage collection before termination in this case. Try master again, I just pushed 6ef7d6d3295c8147401864b087a16fe734fa4bd9

**Comment by legraphista** [comment] 2018-07-07 19:18
Yes, the commit https://github.com/laverdet/isolated-vm/commit/6ef7d6d3295c8147401864b087a16fe734fa4bd9 has fixed the issue. It looks like the memory rises to the limit, then drops back down and cycles.

**Closed** 2018-07-17 07:38 UTC
